---
title: "campaign_events_analysis"
author: "Arielle Ostry"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(plotly)



events <- readRDS("events_saved.rds")

```

## Intro

```{r}

Top10_cities <- events %>% 
  count(city, sort = TRUE) %>% 
  head(10)

Top10_cities
```

```{r}
events %>% filter(cand_lastname == "Harris") %>% 
  group_by(event_type) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  head(5)
  
```

```{r}
events %>% filter(cand_lastname == "Biden") %>% 
  group_by(event_type) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  head(5)
  
```

```{r}
events_month <- events %>% mutate(month(date))

Kamala_months <- events_month %>% filter(cand_lastname == "Harris") %>% 
  group_by(month(date)) %>% 
  count(month = month(date))

Kamala_months
```
```{r}
figure1 <- Kamala_months %>% plot_ly(x = ~month, y = ~n, type = "bar")

figure1_title <- figure1 %>% layout(title = "Total Trips Each Month by Harris")

figure1_title
```
 
